---
title: "P8105 Homework 3"
author: 'Zanis Fang, UID: ZF2213'
date: "10/4/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# ggplot2 tibble dplyr tidyr ... etc.
library(tidyverse)

#install p8105.datasets if not already installed
if (!"p8105.datasets" %in% installed.packages()) {
	devtools::install_github("p8105/p8105.datasets")
}

```

## Problem 1

### Data loading

```{r}
brfss <- p8105.datasets::brfss_smart2010 %>%
         # overall health topic
         filter(Topic == "Overall Health") %>% 
         # select necessary columns
         select(Year, Locationdesc, Response, Data_value) %>% 
         # seperate location into state and area
         separate(Locationdesc, c("state", "area"), sep = " - ") %>% 
         # recode response into factor variable
         mutate(Response = forcats::fct_relevel(Response,
                                                c("Excellent",
                                                  "Very good",
                                                  "Good",
                                                  "Fair",
                                                  "Poor"))) %>%
         # clean column names
         janitor::clean_names() %>% 
         # arrange dataset according to response from excellent to poor
         arrange(response)
 
```

## Problem 2

### Data loading

```{r}
# load data
instacart <- p8105.datasets::instacart
             

```

## Problem 3

### Data loading

```{r}
ny_noaa <- p8105.datasets::ny_noaa
```


